### ISSUE TITLE
Hello Duarte

### ISSUE THREAD

**Issue by ghost** [dmfolgado/tam#2]
Do you have a Matlab function or compatibility with Matlab for your Time Alignment Measurement code?  I'm a postdoc in Canada in neuroscience and want to use your measure in my analysis, but I use Matlab.  Thanks. Annemarie Wolff

**Comment by dmfolgado** [comment]
Hi Annemarie, I don't. To implement in Matlab you'll need a DTW implementation that returns the optimal alignment path and then you will need to adapt the code to count the number of advances, delays and phase. Let me know if you will think of implement in Matlab so I can help you. Nevertheless, there is an R implementation on TAM available at the TSDist package (https://rdrr.io/cran/TSdist/man/TAMDistance.html).
